baseURL = "/"
title = "zxCoder's blog"
theme = "hugo-theme-jijian"
defaultContentLanguage = "zh-cn"

# Pagination
paginate = 6
paginatePath = "page"

enableRobotsTXT = true

[outputs]
  home = ["HTML", "JSON"]

[taxonomies]
  category = "category"
  tag = "tags"

[zh-cn]
  LanguageName = "简体中文"
  contentDir = "content"

[markup]
  [markup.highlight]
    codeFences = false # 关掉默认的code样式，就离谱，居然用内联样式
# https://discourse.gohugo.io/t/unable-to-customize-the-syntax-highlight-colors/22140/3
# https://gohugo.io/getting-started/configuration-markup#highlight
